# Copyright 2020 The Flutter Authors
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

name: extension_google_sign_in_as_googleapis_auth
description: A bridge package between google_sign_in and googleapis_auth, to create Authenticated Clients from google_sign_in user credentials.
version: 2.0.0
homepage: https://github.com/flutter/plugins/google_sign_in/extension_google_sign_in_as_googleapis_auth

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.0-nullsafety
  googleapis_auth: ^1.0.0
  meta: ^1.3.0
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.3
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.4"
