# Copyright 2020 The Flutter Authors
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

name: extension_google_sign_in_as_googleapis_auth
description: A bridge package between google_sign_in and googleapis_auth, to create Authenticated Clients from google_sign_in user credentials.
version: 1.0.0
homepage: https://github.com/flutter/plugins/google_sign_in/extension_google_sign_in_as_googleapis_auth

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.4.1
  googleapis_auth: ^0.2.11+1
  meta: ^1.1.8
  http: ^0.12.1

dev_dependencies:
  mockito: ^4.1.1
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
