name: device_info
description: Provides detailed information about the device the Flutter app is running on.
version: 0.0.4
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/device_info

flutter:
  plugin:
    androidPackage: io.flutter.plugins.deviceinfo
    iosPrefix: FLT
    pluginClass: DeviceInfoPlugin

dependencies:
  flutter:
    sdk: flutter
