name: device_info
description: Flutter plugin providing detailed information about the device
  (make, model, etc.), and Android or iOS version the app is running on.
version: 0.1.0
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/device_info

flutter:
  plugin:
    androidPackage: io.flutter.plugins.deviceinfo
    iosPrefix: FLT
    pluginClass: DeviceInfoPlugin

dependencies:
  flutter:
    sdk: flutter
