name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
version: 4.0.16

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
      ios:
        pluginClass: FLTGoogleSignInPlugin

dependencies:
  google_sign_in_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  http: ^0.12.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
