name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
version: 4.5.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
      ios:
        pluginClass: FLTGoogleSignInPlugin
      web:
        default_package: google_sign_in_web

dependencies:
  google_sign_in_platform_interface: ^1.1.1
  flutter:
    sdk: flutter
  meta: ^1.0.4
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  google_sign_in_web: ^0.9.1

dev_dependencies:
  http: ^0.12.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  integration_test:
    path: ../../integration_test

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
