name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
repository: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_sign_in%22
version: 5.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
      ios:
        pluginClass: FLTGoogleSignInPlugin
      web:
        default_package: google_sign_in_web

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_platform_interface: ^2.0.1
  google_sign_in_web: ^0.10.0
  meta: ^1.3.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
