name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
version: 5.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
      ios:
        pluginClass: FLTGoogleSignInPlugin
      web:
        default_package: google_sign_in_web

dependencies:
  google_sign_in_platform_interface: ^2.0.1
  google_sign_in_web: ^0.10.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  http: ^0.13.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  integration_test:
    path: ../../integration_test

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
