name: image_picker

description: Flutter plugin that shows an image picker and uses the camera.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/image_picker
version: 0.1.4

flutter:
  plugin:
    androidPackage: io.flutter.plugins.imagepicker
    iosPrefix: FLT
    pluginClass: ImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
