name: google_maps_flutter
description: A Flutter plugin for integrating Google Maps in iOS and Android applications.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter
version: 0.0.3+3

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.googlemaps
    iosPrefix: FLT
    pluginClass: GoogleMapsPlugin


environment:
  sdk: ">=2.0.0-dev.47.0 <3.0.0"
  flutter: ">=0.11.9 <2.0.0"
