name: url_launcher_linux
description: Linux implementation of the url_launcher plugin.
version: 2.0.0
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_linux

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: UrlLauncherPlugin

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
