name: url_launcher_linux
description: Linux implementation of the url_launcher plugin.
version: 0.1.0-nullsafety.1
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_linux

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: UrlLauncherPlugin

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.8"

dependencies:
  flutter:
    sdk: flutter
