name: url_launcher_linux
description: Linux implementation of the url_launcher plugin.
repository: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_linux
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22
version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: url_launcher
    platforms:
      linux:
        pluginClass: UrlLauncherPlugin

dependencies:
  flutter:
    sdk: flutter
