name: shared_preferences_linux_example
description: Demonstrates how to use the shared_preferences_linux plugin.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any

dependency_overrides:
  shared_preferences_linux:
    path: ../
  shared_preferences_platform_interface:
    path: ../../shared_preferences_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    path: ../../../integration_test
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
