name: shared_preferences_linux
description: Linux implementation of the shared_preferences plugin
version: 0.0.4-nullsafety
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_linux

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: SharedPreferencesLinux
        pluginClass: none

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"
  flutter: ">=1.12.8"

dependencies:
  file: ">=6.0.0-nullsafety.4 <7.0.0"
  flutter:
    sdk: flutter
  meta: ^1.0.4
  path_provider_linux: ^0.2.0-nullsafety
  shared_preferences_platform_interface: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
