name: google_maps_flutter
description: A Flutter plugin for integrating Google Maps in iOS and Android applications.
repository: https://github.com/flutter/plugins/tree/main/packages/google_maps_flutter/google_maps_flutter
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+maps%22
version: 2.3.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: google_maps_flutter_android
      ios:
        default_package: google_maps_flutter_ios

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_android: ^2.1.10
  google_maps_flutter_ios: ^2.1.10
  google_maps_flutter_platform_interface: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  stream_transform: ^2.0.0


# FOR TESTING ONLY. DO NOT MERGE.
dependency_overrides:
  google_maps_flutter_android:
    path: ../google_maps_flutter_android
  google_maps_flutter_ios:
    path: ../google_maps_flutter_ios
  google_maps_flutter_platform_interface:
    path: ../google_maps_flutter_platform_interface
