name: wifi_info_flutter_platform_interface
description: A common platform interface for the wifi_info_flutter plugin.
version: 1.0.0
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
homepage: https://github.com/flutter/plugins/tree/master/packages/wifi_info_flutter/wifi_info_flutter_platform_interface

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  plugin_platform_interface: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter
