name: share
description: Flutter plugin for sharing content via the platform share UI, using
  the ACTION_SEND intent on Android and UIActivityViewController on iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/share
version: 2.0.0-nullsafety.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.share
        pluginClass: SharePlugin
      ios:
        pluginClass: FLTSharePlugin

dependencies:
  meta: ^1.3.0-nullsafety.6
  mime: ^1.0.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter
  integration_test:
    path: ../integration_test
  pedantic: ^1.10.0-nullsafety.3

environment:
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0-0 <3.0.0"
