name: share
description: Flutter plugin for sharing content via the platform share UI, using
  the ACTION_SEND intent on Android and UIActivityViewController on iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/share
version: 2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.share
        pluginClass: SharePlugin
      ios:
        pluginClass: FLTSharePlugin

dependencies:
  meta: ^1.3.0
  mime: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  flutter: ">=1.12.13+hotfix.5"
  sdk: ">=2.12.0 <3.0.0"
