name: path_provider_macos
description: macOS implementation of the path_provider plugin
version: 2.0.0
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: PathProviderPlugin

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
