name: camera
description: A Flutter plugin for getting information about and controlling the
  camera on Android and iOS. Supports previewing the camera feed, capturing images, capturing video,
  and streaming image buffers to dart.
version: 0.8.1
homepage: https://github.com/flutter/plugins/tree/master/packages/camera/camera

dependencies:
  flutter:
    sdk: flutter

  camera_platform_interface: ^2.0.1
  pedantic: ^1.10.0
  quiver: ^3.0.0-nullsafety.3

dev_dependencies:
  video_player: ^2.0.0-nullsafety.7
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.5
  plugin_platform_interface: ^1.1.0-nullsafety.2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.22.0"
