name: sensors

version: 0.1.0
description: A Flutter plugin to access the accelerometer and gyroscope sensors.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/sensors

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sensors
    iosPrefix: FLT
    pluginClass: SensorsPlugin

dependencies:
  flutter:
    sdk: flutter
