name: sensors
description: Flutter plugin for accessing the Android and iOS accelerometer and
  gyroscope sensors.
homepage: https://github.com/flutter/plugins/tree/master/packages/sensors
version: 0.4.1+4

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FLTSensorsPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  e2e: ^0.2.0
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
