name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  firebase_performance:
    path: ../
  firebase_core: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any



flutter:
  uses-material-design: true
