name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences
version: 0.5.4+7

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sharedpreferences
    iosPrefix: FLT
    pluginClass: SharedPreferencesPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.6.7 <2.0.0"
