name: image_picker_example
description: Demonstrates how to use the image_picker plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
publish_to: 'none'

dependencies:
  video_player: ^0.10.3
  flutter:
    sdk: flutter
  image_picker:
    # When depending on this package from a real application you should use:
    #   image_picker: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter_plugin_android_lifecycle: ^1.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e:  ^0.2.1
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
