name: shared_preferences_windows
description: Windows implementation of shared_preferences
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_windows
version: 2.0.0


flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: SharedPreferencesWindows
        pluginClass: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  shared_preferences_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  file: ^6.0.0
  meta: ^1.3.0
  path: ^1.8.0
  path_provider_platform_interface: ^2.0.0
  path_provider_windows: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
