name: shared_preferences_windows
description: Web platform implementation of shared_preferences
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_windows
version: 0.0.1

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: SharedPreferencesWindows

dependencies:
  shared_preferences_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.1.7
  ffi: ^0.1.3
  file: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
