name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  camera_platform_interface: ^2.1.0
  camera_web:
    path: ../
  cross_file: ^0.3.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
