name: image_picker_platform_interface
description: A common platform interface for the image_picker plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.1.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  http: ^0.12.1
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
