name: firebase_ml_vision
description: Flutter plugin for Google ML Vision for Firebase, an SDK that brings Google's machine
  learning expertise to Android and iOS apps in a powerful yet easy-to-use package.
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebasemlvision
    iosPrefix: FLT
    pluginClass: FirebaseMlVisionPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
