name: google_sign_in_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_web:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  integration_test:
    sdk: flutter
  js: ^0.6.3
