name: path_provider

version: 0.2.0
description: A Flutter plugin for getting commonly used locations on the filesystem.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider

flutter:
  plugin:
    androidPackage: io.flutter.plugins.path_provider
    pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
