name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
version: 0.2.1
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player

flutter:
  plugin:
    androidPackage: io.flutter.plugins.videoplayer
    iosPrefix: FLT
    pluginClass: VideoPlayerPlugin

dependencies:
  meta: "^1.0.5"
  flutter:
    sdk: flutter

environment:
  sdk: ">=1.8.0 <2.0.0"
