name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
repository: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 2.0.15

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_platform_interface: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

