name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
repository: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 2.3.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
  #TODO (BeMacized): CHANGE TO VERSION DEPENDENCY ONCE UPDATED PLATFORM INTERFACE HAS BEEN PUBLISHED.
  webview_flutter_platform_interface:
    path: ../webview_flutter_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pigeon: 1.0.10
  pedantic: ^1.10.0
  mockito: ^5.0.16
  build_runner: ^2.1.5

