name: camera_platform_interface
description: A common platform interface for the camera plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/camera/camera_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ">=1.0.0 <3.0.0"
  cross_file: ^0.3.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  async: ^2.5.0
  pedantic: ^1.10.0

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.22.0"
