name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
# 0.10.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 2.0.0-nullsafety.3
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.3.0-nullsafety.3
  video_player_platform_interface: ^3.0.0-nullsafety.2

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: ^2.0.0-nullsafety.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.1
  pigeon: 0.1.7

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
