name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
version: 2.0.2
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player
publish_to: none

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.3.0
  video_player_platform_interface:
    path: ../video_player_platform_interface

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint. The exact value doesn't matter since
  # the constraints on the interface pins it.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web:
    path: ../video_player_web

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^0.1.21

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
