name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android and iOS.
version: 0.11.0
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: "^1.0.5"
  video_player_platform_interface: #^2.0.0
    # workaround for success build checks in PR
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: reusable_video_controller
      path: packages/video_player/video_player_platform_interface
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: #^0.2.0
    # workaround for success build checks in PR
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: reusable_video_controller
      path: packages/video_player/video_player_web

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
