name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
# 0.10.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.11.1
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: FLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.0.5
  video_player_platform_interface:
    git:
      url: https://github.com/severgroup-tt/plugins.git
      path: packages/video_player/video_player_platform_interface
      ref: master
  video_player_web:
    git:
      url: https://github.com/severgroup-tt/plugins.git
      path: packages/video_player/video_player_web
      ref: master
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  pigeon: 0.1.7

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
