name: path_provider_windows
description: Windows implementation of the path_provider plugin
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_windows
version: 0.0.4+2

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: PathProviderWindows
        pluginClass: none

dependencies:
  path_provider_platform_interface: ^1.0.3
  meta: ^1.0.5
  path: ^1.6.4
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  win32: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
