name: path_provider_windows
description: Windows implementation of the path_provider plugin
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_windows
version: 2.0.0-nullsafety.1

flutter:
  plugin:
    implements: path_provider
    platforms:
      windows:
        dartPluginClass: PathProviderWindows
        pluginClass: none

dependencies:
  path_provider_platform_interface: ^2.0.0-nullsafety
  meta: ^1.3.0-nullsafety.6
  path: ^1.8.0-nullsafety.3
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  win32: ^2.0.0-nullsafety.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"
