name: video_player_example
description: Demonstrates how to use the video_player plugin.

dependencies:
  flutter:
    sdk: flutter
  video_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: "^0.2.0"
  test: any

flutter:
  uses-material-design: true
  assets:
   - assets/flutter-mark-square-64.png
   - assets/Butterfly-209.mp4
   - assets/bumble_bee_captions.srt
