name: file_selector_platform_interface
description: A common platform interface for the file_selector plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/file_selector/file_selector_platform_interface
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  cross_file: ^0.3.0
  flutter:
    sdk: flutter
  http: ^0.13.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.3
