name: file_selector_platform_interface
description: A common platform interface for the file_selector plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.2

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  http: ^0.12.0+1
  plugin_platform_interface: ^1.0.1
  cross_file: ^0.1.0

dev_dependencies:
  test: ^1.15.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
