name: cross_file
description: An abstraction to allow working with files across multiple platforms.
homepage: https://github.com/flutter/plugins/tree/master/packages/cross_file
version: 0.1.0+2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  meta: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.22.0"
