name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 2.0.0-nullsafety.3
homepage: https://github.com/flutter/plugins/tree/master/packages/webview_flutter


environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: FLTWebViewFlutterPlugin
