name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
homepage: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase
version: 0.5.2

# TODO(mvanbeusekom): Remove when in_app_purchase_platform_interface is published
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  meta: ^1.3.0
  collection: ^1.15.0

  # TODO(mvanbeusekom): Replace with pub.dev version when in_app_purchase_platform_interface is published
  in_app_purchase_platform_interface:
    path: ../in_app_purchase_platform_interface

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.0
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.inapppurchase
        pluginClass: InAppPurchasePlugin
      ios:
        pluginClass: InAppPurchasePlugin

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
