name: firebase_analytics

description: Firebase Analytics plugin for Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_analytics
version: 0.1.1

flutter:
  plugin:
    androidPackage: io.flutter.firebaseanalytics
    pluginClass: FirebaseAnalyticsPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.24+8

environment:
    sdk: ">=1.8.0 <2.0.0"
