name: firebase_analytics
description: Firebase Analytics plugin for Flutter.

flutter:
  plugin:
    androidPackage: io.flutter.firebase_analytics
    pluginClass: FirebaseAnalyticsPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: ^0.12.20
