name: firebase_analytics
description: Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_analytics

version: 0.2.3

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseanalytics
    iosPrefix: FLT
    pluginClass: FirebaseAnalyticsPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.30+4

environment:
    sdk: ">=1.8.0 <2.0.0"
