name: shared_preferences

version: 0.2.5+1
description: A Flutter plugin for reading and writing simple key-value pairs.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sharedpreferences
    pluginClass: SharedPreferencesPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
