name: device_info
description: Flutter plugin providing detailed information about the device
  (make, model, etc.), and Android or iOS version the app is running on.
homepage: https://github.com/flutter/plugins/tree/master/packages/device_info
# 0.4.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.5.0-nullsafety

# Don't publish this package until null safety is stable or the package is in the allow list.
publish_to: none

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.deviceinfo
        pluginClass: DeviceInfoPlugin
      ios:
        pluginClass: FLTDeviceInfoPlugin

dependencies:
  flutter:
    sdk: flutter
  device_info_platform_interface:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: device_info/device_info_platform_interface
dev_dependencies:
  test: ^1.10.0-nullsafety.1
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
