name: firebase_messaging

description: Firebase Cloud Messaging plugin for Flutter applications.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_messaging
version: 0.0.7

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebasemessaging
    pluginClass: FirebaseMessagingPlugin

dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.24+8

environment:
  sdk: ">=1.8.0 <2.0.0"
