name: firebase_auth

description: Firebase Auth plugin for Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_auth
version: 0.0.2

flutter:
  plugin:
    androidPackage: io.flutter.firebase_auth
    pluginClass: FirebaseAuthPlugin

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: ^0.12.20

environment:
    sdk: ">=1.8.0 <2.0.0"
