name: battery_platform_interface
description: A common platform interface for the battery plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/battery
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0-nullsafety

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  plugin_platform_interface: ^1.1.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.0
  pedantic: ^1.10.0-nullsafety.3

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4"
