name: google_sign_in_platform_interface
description: A common platform interface for the google_sign_in plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  quiver_hashcode: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
