name: google_sign_in_platform_interface
description: A common platform interface for the google_sign_in plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0-nullsafety

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  quiver: ^3.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
