name: local_auth
description: Flutter plugin for Android and iOS devices to allow local
  authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
repository: https://github.com/flutter/plugins/tree/main/packages/local_auth/local_auth
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 1.1.11

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  intl: ^0.17.0
  platform: ^3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
