name: example
description: Example for file_selector_ios implementation.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  file_selector_ios:
    # When depending on this package from a real application you should use:
    #   file_selector_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ..
  file_selector_platform_interface: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true