name: google_maps_flutter_platform_interface
description: A common platform interface for the google_maps_flutter plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0-nullsafety

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^1.1.0-nullsafety.2
  stream_transform: ^2.0.0-nullsafety.0
  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.0
  pedantic: ^1.8.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.9.1+hotfix.4"
