name: android_alarm_manager
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
version: 0.2.2
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager

dependencies:
  firebase_auth: ^0.6.6
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.androidalarmmanager
    pluginClass: AndroidAlarmManagerPlugin
    iosPrefix: FLT

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
