name: android_alarm_manager
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
version: 0.4.5
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.androidalarmmanager
        pluginClass: AndroidAlarmManagerPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  # TODO(bkonyi): set minimum Flutter version to next stable release
  flutter: ">=1.2.0 <2.0.0"
