name: android_intent
description: Flutter plugin for launching Android Intents. Not supported on iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/android_intent
version: 2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.androidintent
        pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.0.0
  meta: ^1.3.0
dev_dependencies:
  test: ^1.16.3
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  build_runner: ^1.11.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
