name: android_intent
description: A plugin for launching Intents on Android.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/android_intent
version: 0.0.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.androidintent
    iosPrefix: FLT
    pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^2.0.0
  meta: ^1.0.5

environment:
  sdk: ">=1.8.0 <2.0.0"
