name: integration_test_example
description: Demonstrates how to use the integration_test plugin.
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.6.7"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    # When depending on this package from a real application you should use:
    #   integration_test: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  test: any
  pedantic: ^1.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
