name: firebase_storage

description: Firebase Storage plugin for Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_storage
version: 0.0.8

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.storage
    iosPrefix: FLT
    pluginClass: FirebaseStoragePlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
