name: connectivity_macos
description: macOS implementation of the connectivity plugin.
version: 2.0.0-nullsafety.1
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity_macos

flutter:
  plugin:
    implements: connectivity
    platforms:
      macos:
        pluginClass: ConnectivityPlugin

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
