name: file_selector_web
description: Web platform implementation of file_selector
repository: https://github.com/flutter/plugins/tree/main/packages/file_selector/file_selector_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.9.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      web:
        pluginClass: FileSelectorWeb
        fileName: file_selector_web.dart

dependencies:
  file_selector_platform_interface: ^2.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
