name: file_selector_web
description: Web platform implementation of file_selector
homepage: https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector_web
version: 1.0.0-nullsafety.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FileSelectorWeb
        fileName: file_selector_web.dart

dependencies:
  file_selector_platform_interface: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  integration_test:
    sdk: flutter
  build_runner: ^1.10.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.26.0-0"
