name: google_sign_in

description: Google Sign-In plugin for Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in
version: 1.0.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.googlesignin
    iosPrefix: FLT
    pluginClass: GoogleSignInPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
