name: in_app_purchase_ios
description: An implementation for the iOS platform of the Flutter `in_app_purchase` plugin. This uses the iOS StoreKit Framework.
repository: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/in_app_purchase_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 0.1.3+4

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: in_app_purchase
    platforms:
      ios:
        pluginClass: InAppPurchasePlugin

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.1.0
  json_annotation: ^4.0.1
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.1
  test: ^1.16.0
