name: in_app_purchase_ios
description: An implementation for the iOS platform of the Flutter `in_app_purchase` plugin. This uses the iOS StoreKit Framework.
repository: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/in_app_purchase_ios
version: 0.1.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: InAppPurchasePlugin

dependencies:
  in_app_purchase_platform_interface: ^1.0.0
  
  flutter:
    sdk: flutter

  meta: ^1.3.0
  test: ^1.16.0
  
dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.1.1
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
