name: cloud_functions
description: Flutter plugin for Cloud Functions.
version: 0.1.0
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/cloud_functions

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.cloudfunctions.cloudfunctions
    pluginClass: CloudFunctionsPlugin

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.3.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
