name: flutter_plugin_tools
description: Productivity utils for hosting multiple plugins within one repository.
publish_to: none

dependencies:
  args: "^1.4.3"
  path: "^1.6.1"
  http: "^0.12.1"
  async: "^2.0.7"
  yaml: "^2.1.15"
  quiver: "^2.0.2"
  pub_semver: ^1.4.2
  colorize: ^2.0.0
  git: ^1.0.0
  platform: ^2.2.0
  pubspec_parse: "^0.1.4"
  test: ^1.6.4
  meta: ^1.1.7
  file: ^5.0.10
  uuid: ^2.0.4
  http_multi_server: ^2.2.0
  collection: 1.14.13

dev_dependencies:
  matcher: ^0.12.6
  mockito: ^4.1.1
  pedantic: 1.8.0

environment:
  sdk: ">=2.3.0 <3.0.0"
