name: flutter_plugin_tools
description: Productivity utils for flutter/plugins and flutter/packages
repository: https://github.com/flutter/plugins/tree/main/script/tool
version: 0.13.4+2

dependencies:
  args: ^2.1.0
  async: ^2.6.1
  collection: ^1.15.0
  colorize: ^3.0.0
  file: ^6.1.0
  # Pin git to 2.0.x until dart >=2.18 is legacy
  git: '>=2.0.0 <2.1.0'
  http: ^0.13.3
  http_multi_server: ^3.0.1
  meta: ^1.3.0
  path: ^1.8.0
  platform: ^3.0.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  quiver: ^3.0.1
  test: ^1.17.3
  uuid: ^3.0.4
  yaml: ^3.1.0
  yaml_edit: ^2.0.2

dev_dependencies:
  build_runner: ^2.0.3
  matcher: ^0.12.10
  mockito: ^5.0.7

environment:
  sdk: '>=2.12.0 <3.0.0'
