name: google_maps_flutter_example
description: Demonstrates how to use the google_maps_flutter plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  google_maps_flutter_android:
    # When depending on this package from a real application you should use:
    #   google_maps_flutter_android: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  google_maps_flutter_platform_interface: ^2.2.1

dev_dependencies:
  build_runner: ^2.1.10
  espresso: ^0.1.0+2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
