name: connectivity
description: Allows developers to discover the state of the network connectivity.
version: 0.2.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity

flutter:
  plugin:
    androidPackage: io.flutter.plugins.connectivity
    iosPrefix: FLT
    pluginClass: ConnectivityPlugin

dependencies:
  flutter:
    sdk: flutter
