name: connectivity
description: Flutter plugin for discovering the state of the network (WiFi &
  mobile/cellular) connectivity on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity
version: 0.4.2+2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.connectivity
    iosPrefix: FLT
    pluginClass: ConnectivityPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.0.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.2.0 <2.0.0"
