name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
repository: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 2.4.0

# TODO(mvanbeusekom): Remove once https://github.com/flutter/plugins/pull/4544 has landed and path dependency has been removed
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  # TODO(mvanbeusekom): Remove path dependency once https://github.com/flutter/plugins/pull/4544 has landed
  webview_flutter_android:
    path: ../webview_flutter_android
  webview_flutter_platform_interface: ^1.5.2
  webview_flutter_wkwebview: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
