name: flutter_webview_pro
description: A Flutter plugin that provides a WebView widget who Support photo upload/take camera and Geolocation.一个在Flutter上支持图片上传、相机拍照、地理定位的webview插件
repository: https://github.com/wenzhiming/flutter-plugins/tree/dev/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/wenzhiming/flutter-plugins/issues
version: 3.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android:
    path: ../webview_flutter_android
  webview_flutter_platform_interface:
    path: ../webview_flutter_platform_interface
  webview_flutter_wkwebview:
    path: ../webview_flutter_wkwebview

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
