name: google_maps_flutter_web
description: Web platform implementation of google_maps_flutter
homepage: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter
version: 0.1.0+7

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GoogleMapsPlugin
        fileName: google_maps_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  google_maps_flutter_platform_interface: ^1.0.4
  google_maps: ^3.4.5
  stream_transform: ^1.2.0
  sanitize_html: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.2.5
  pedantic: ^1.8.0
  mockito: ^4.1.1
  integration_test:
    path: ../../integration_test

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
