name: quick_actions_platform_interface
description: A common platform interface for the quick_actions plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/quick_actions/quick_actions_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  pedantic: ^1.11.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.22.0"
