name: wifi_info_flutter
description: A new flutter plugin project.
homepage: https://github.com/flutter/plugins/tree/master/packages/wifi_info_flutter/wifi_info_flutter
version: 2.0.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  wifi_info_flutter_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.wifi_info_flutter
        pluginClass: WifiInfoFlutterPlugin
      ios:
        pluginClass: WifiInfoFlutterPlugin
