name: google_sign_in_web
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android, iOS and Web.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web
version: 0.10.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GoogleSignInPlugin
        fileName: google_sign_in_web.dart

dependencies:
  google_sign_in_platform_interface: ^2.0.0-0 # TODO: Migrate to stable
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.20.0"
