name: google_sign_in_web
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android, iOS and Web.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web
version: 0.8.4

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GoogleSignInPlugin
        fileName: google_sign_in_web.dart

dependencies:
  google_sign_in_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  js: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.0.14
  pedantic: ^1.8.0

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
