name: file_selector_ios
description: iOS implementation of the file_selector plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/file_selector/file_selector_ios
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.5.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      ios:
        dartPluginClass: FileSelectorIOS
        pluginClass: FFSFileSelectorPlugin

dependencies:
  file_selector_platform_interface: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.1.11
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  pigeon: ^3.2.5
  
