name: in_app_purchase_storekit
description: An implementation for the iOS platform of the Flutter `in_app_purchase` plugin. This uses the StoreKit Framework.
repository: https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase_storekit
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 0.3.2

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: in_app_purchase
    platforms:
      ios:
        pluginClass: InAppPurchasePlugin

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.3.0
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  test: ^1.16.0
