name: battery
description: Flutter plugin for accessing information about the battery state
  (full, charging, discharging) on Android and iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/battery
version: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.battery
        pluginClass: BatteryPlugin
      ios:
        pluginClass: FLTBatteryPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  async: ^2.0.8
  test: ^1.3.0
  mockito: 3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    path: ../integration_test
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
