name: battery
description: Flutter plugin for accessing information about the battery state
  (full, charging, discharging) on Android and iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/battery
version: 0.3.1+7

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.battery
        pluginClass: BatteryPlugin
      ios:
        pluginClass: FLTBatteryPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  async: ^2.0.8
  test: ^1.3.0
  mockito: 3.0.0
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
