name: path_provider
description: Flutter plugin for getting commonly used locations on the Android &
  iOS file systems, such as the temp and app data directories.
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider
version: 1.6.14

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.pathprovider
        pluginClass: PathProviderPlugin
      ios:
        pluginClass: FLTPathProviderPlugin
      macos:
        default_package: path_provider_macos
      linux:
        default_package: path_provider_linux

dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface: ^1.0.1
  path_provider_macos: ^0.0.4
  path_provider_linux: ^0.0.1

dev_dependencies:
  integration_test:
    path: ../../integration_test
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  uuid: "^1.0.0"
  pedantic: ^1.8.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
