name: file_selector
description: Flutter plugin for opening and saving files, or selecting
  directories, using native file selection UI.
repository: https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.8.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: file_selector_web

dependencies:
  file_selector_platform_interface: ^2.0.0
  file_selector_web: ^0.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.3
