name: file_selector
description: Flutter plugin for opening and saving files.
homepage: https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector
version: 0.8.2

flutter:
  plugin:
    platforms:
      web:
        default_package: file_selector_web

dependencies:
  flutter:
    sdk: flutter
  file_selector_platform_interface: ^2.0.2
  file_selector_web: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.3
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.20.0"
