name: video_player_web
description: Web platform implementation of video_player
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player_web
version: 0.2.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  video_player_platform_interface: #^2.0.0
    # workaround for success build checks in PR
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: reusable_video_controller
      path: packages/video_player/video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player:
    path: ../video_player
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
