name: video_player_web
description: Web platform implementation of video_player.
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player_web
version: 2.0.0-nullsafety.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0-nullsafety.3
  video_player_platform_interface: ^3.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player:
    path: ../video_player
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.8"
