name: image_picker_for_web
description: Web platform implementation of image_picker
homepage: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker_for_web

version: 2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ImagePickerPlugin
        fileName: image_picker_for_web.dart

dependencies:
  image_picker_platform_interface: ^2.0.0
  meta: ^1.3.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
