name: url_launcher_example
description: Demonstrates how to use the url_launcher plugin.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: any
  url_launcher_linux:
    path: ../

dev_dependencies:
  integration_test:
    path: ../../../integration_test
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
