name: connectivity_example
description: Demonstrates how to use the connectivity plugin.

dependencies:
  flutter:
    sdk: flutter
  connectivity:
    path: ../
  connectivity_macos:
    path: ../connectivity_macos

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0

flutter:
  uses-material-design: true
