name: battery_example
description: Demonstrates how to use the battery plugin.

dependencies:
  flutter:
    sdk: flutter
  battery:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1

flutter:
  uses-material-design: true
