name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: 'none'

dependencies:
  camera:
    # When depending on this package from a real application you should use:
    #   camera: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  path_provider: ^0.5.0
  flutter:
    sdk: flutter
  video_player: ^0.10.0
  integration_test:
    path: ../../../integration_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4"
