name: file_selector_web_integration_tests
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  file_selector_web:
    path: ../
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.27.0-0" # For integration_test from sdk
