name: path_provider_example
description: Demonstrates how to use the path_provider plugin.

dependencies:
  flutter:
    sdk: flutter
  path_provider:
    path: ../
  path_provider_macos:
    path: ../../path_provider_macos

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
