name: path_provider_example
description: Demonstrates how to use the path_provider plugin.
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  path_provider:
    # When depending on this package from a real application you should use:
    #   path_provider: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

# TODO(egarciad): Remove the overrides once the packages are published.
dependency_overrides:
  path_provider_macos:
    path: ../../path_provider_macos
  path_provider_linux:
    path: ../../path_provider_linux
  path_provider_windows:
    path: ../../path_provider_windows

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
