name: example
description: Example for file_selector_macos implementation.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  file_selector_macos:
    # When depending on this package from a real application you should use:
    #   file_selector_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ..
  # TODO(VanesaOshiro): This should be 2.3.0 once it is published.
  file_selector_platform_interface:
    path: ../../file_selector_platform_interface/
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
