name: path_provider
description: Flutter plugin for getting commonly used locations on the Android &
  iOS file systems, such as the temp and app data directories.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider
version: 0.5.0

flutter:
  plugin:
    androidPackage: io.flutter.plugins.pathprovider
    iosPrefix: FLT
    pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
