name: quick_actions
description: Flutter plugin for creating shortcuts on home screen, also known as
  Quick Actions on iOS and App Shortcuts on Android.
homepage: https://github.com/flutter/plugins/tree/master/packages/quick_actions
version: 0.5.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.quickactions
        pluginClass: QuickActionsPlugin
      ios:
        pluginClass: FLTQuickActionsPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
