name: quick_actions
description: Flutter plugin for creating shortcuts on home screen, also known as
  Quick Actions on iOS and App Shortcuts on Android.
repository: https://github.com/flutter/plugins/tree/main/packages/quick_actions/quick_actions
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+quick_actions%22
version: 0.6.0+9

# Temporarily disable publishing to allow moving Android and iOS
# implementations.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.quickactions
        pluginClass: QuickActionsPlugin
      ios:
        default_package: quick_actions_ios

dependencies:
  flutter:
    sdk: flutter
  # Temporary path dependencies to allow moving Android and iOS implementations.
  quick_actions_ios:
    path: ../quick_actions_ios
  quick_actions_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.7
  pedantic: ^1.11.0
  plugin_platform_interface: ^2.0.0
