name: webview_flutter_example
description: Demonstrates how to use the webview_flutter plugin.

version: 1.0.2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: "^0.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
