name: quick_actions_example
description: Demonstrates how to use the quick_actions plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  quick_actions:
    # When depending on this package from a real application you should use:
    #   quick_actions: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  espresso: ^0.1.0+2
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
