name: url_launcher_platform_interface
description: A common platform interface for the url_launcher plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0-nullsafety.1

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.1.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
