name: path_provider_example
description: Demonstrates how to use the path_provider plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.14

# path_provider_macos is endorsed, so we need to add it to dependency_overrides
# to depend on it from path:
dependency_overrides:
  path_provider_macos:
    # When depending on this package from a real application you should use:
    #   path_provider_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  integration_test:
    path: ../../../integration_test
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"
