name: in_app_purchase_android
description: An implementation for the Android platform of the Flutter `in_app_purchase` plugin. This uses the Android BillingClient APIs.
repository: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/in_app_purchase_android
version: 0.1.0

# TODO(mvanbeusekom): Remove when in_app_purchase_platform_interface is published
publish_to: 'none'

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.inapppurchase
        pluginClass: InAppPurchasePlugin

dependencies:
  # TODO(mvanbeusekom): Replace with pub.dev version when in_app_purchase_platform_interface is published
  in_app_purchase_platform_interface:
    path: ../in_app_purchase_platform_interface

  flutter:
    sdk: flutter

  json_annotation: ^4.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  test: ^1.16.0

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.1.1
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"