name: audio_player
description: Flutter plugin for displaying inline music with other Flutter
  widgets on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
version: 0.0.1
homepage: https://github.com/flutter/plugins/tree/master/packages/audio_player

flutter:
  plugin:
    androidPackage: io.flutter.plugins.audioplayer
    iosPrefix: FLT
    pluginClass: AudioPlayerPlugin

dependencies:
  meta: "^1.0.5"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.5 <2.0.0"
