name: camera
description: A Flutter plugin for getting information about and controlling the
  camera on Android and iOS. Supports previewing the camera feed and capturing images.
version: 0.2.8
authors:
  - Flutter Team <flutter-dev@googlegroups.com>
  - Luigi Agosti <luigi@tengio.com>
  - Quentin Le Guennec <quentin@tengio.com>
  - Koushik Ravikumar <koushik@tengio.com>
  - Nissim Dsilva <nissim@tengio.com>

homepage: https://github.com/flutter/plugins/tree/master/packages/camera

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^0.4.1
  video_player: ^0.5.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.camera
    pluginClass: CameraPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
