name: in_app_purchase_storekit_example
description: Demonstrates how to use the in_app_purchase_storekit plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.0.0
  in_app_purchase_storekit:
    # When depending on this package from a real application you should use:
    #   in_app_purchase_storekit: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
