name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager:
    # When depending on this package from a real application you should use:
    #   android_alarm_manager: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  shared_preferences: ^0.5.6
  integration_test:
    path: ../../integration_test
  path_provider: ^1.3.1

dev_dependencies:
  espresso: ^0.0.1+3
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
