name: firebase_database

description: Firebase Database plugin for Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_database
version: 0.3.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.database
    iosPrefix: FLT
    pluginClass: FirebaseDatabasePlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.0.1
  meta: "^1.0.5"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
