name: url_launcher_macos
description: macOS implementation of the url_launcher plugin.
version: 2.0.1
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_macos

flutter:
  plugin:
    implements: url_launcher
    platforms:
      macos:
        pluginClass: UrlLauncherPlugin
        fileName: url_launcher_macos.dart

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
