name: url_launcher
description: Flutter plugin for launching a URL on Android and iOS. Supports
  web, phone, SMS, and email schemes.
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
version: 5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: UrlLauncherPlugin
      ios:
        pluginClass: FLTURLLauncherPlugin
      web:
        default_package: url_launcher_web 
      macos:
        default_package: url_laucher_macos

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: ^1.0.4
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  url_launcher_web: ^0.1.0+1
  url_launcher_macos: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
