name: url_launcher
description: Flutter plugin for launching a URL. Supports
  web, phone, SMS, and email schemes.
repository: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22
version: 6.0.11

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: UrlLauncherPlugin
      ios:
        pluginClass: FLTURLLauncherPlugin
      linux:
        default_package: url_laucher_linux
      macos:
        default_package: url_laucher_macos
      web:
        default_package: url_launcher_web
      windows:
        default_package: url_laucher_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # implementation constraints as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  url_launcher_linux: ^2.0.0
  url_launcher_macos: ^2.0.0
  url_launcher_platform_interface: ^2.0.3
  url_launcher_web: ^2.0.0
  url_launcher_windows: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.10.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.3
