name: url_launcher_example
description: Demonstrates how to use the url_launcher plugin.

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
    path: ../

dev_dependencies:
  e2e: "^0.2.0"
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  flutter: ">=1.9.1+hotfix.2 <2.0.0"
