name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
homepage: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase
version: 0.4.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  meta: ^1.3.0-nullsafety.6
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.0
  integration_test:
    path: ../integration_test
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.inapppurchase
        pluginClass: InAppPurchasePlugin
      ios:
        pluginClass: InAppPurchasePlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
