name: local_auth
description: Flutter plugin for Android and iOS devices to allow local
  authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
homepage: https://github.com/flutter/plugins/tree/master/packages/local_auth
version: 1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: 1.3.0-nullsafety.3
  intl: ^0.16.0
  platform: 3.0.0-nullsafety.2
  flutter_plugin_android_lifecycle: ^1.0.11

dev_dependencies:
  integration_test:
    path: ../integration_test
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

environment:
  sdk: ">=2.10.0 <3.0.0"
