name: local_auth
description: Flutter plugin for Android and iOS device authentication sensors
  such as Fingerprint Reader and Touch ID.
homepage: https://github.com/flutter/plugins/tree/master/packages/local_auth
version: 0.6.3+5

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.3
  intl: ^0.17.0-nullsafety.2
  platform: ">=2.0.0 <4.0.0"
  flutter_plugin_android_lifecycle: ^1.0.2

dev_dependencies:
  integration_test:
    path: ../integration_test
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
