name: local_auth
description: Flutter plugin for Android and iOS devices to allow local
  authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
homepage: https://github.com/flutter/plugins/tree/master/packages/local_auth
version: 1.1.4

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  intl: ^0.17.0
  platform: ^3.0.0
  flutter_plugin_android_lifecycle: ^2.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
