name: local_auth
description: A plugin that uses local sensors to authenticate users (such as Fingerprint Reader/Touch ID).
version: 0.0.2+1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/local_auth

flutter:
  plugin:
    androidPackage: io.flutter.plugins.localauth
    iosPrefix: FLT
    pluginClass: LocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  intl: ^0.15.1

environment:
  sdk: ">=1.8.0 <2.0.0"
