name: in_app_purchase_example
description: Demonstrates how to use the in_app_purchase plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  test: 1.5.1
  flutter_driver:
    sdk: flutter
  in_app_purchase:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.4.4 <2.0.0"
