name: in_app_purchase_example
description: Demonstrates how to use the in_app_purchase plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2

dev_dependencies:
  test: ^1.5.2
  flutter_driver:
    sdk: flutter
  in_app_purchase:
    # When depending on this package from a real application you should use:
    #   in_app_purchase: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  integration_test:
    path: ../../integration_test
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2"
