name: in_app_purchase_example
description: Demonstrates how to use the in_app_purchase plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  in_app_purchase:
    # When depending on this package from a real application you should use:
    #   in_app_purchase: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  integration_test:
    path: ../../integration_test
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2"
