name: package_info_example
description: Demonstrates how to use the package_info plugin.

dependencies:
  flutter:
    sdk: flutter
  package_info:
    path: ../
  e2e:
    path: ../../e2e

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
