name: package_info
description: Flutter plugin for querying information about the application
  package, such as CFBundleVersion on iOS or versionCode on Android.
version: 0.1.0
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/package_info

flutter:
  plugin:
    androidPackage: io.flutter.plugins.packageinfo
    iosPrefix: FLT
    pluginClass: PackageInfoPlugin

dependencies:
  flutter:
    sdk: flutter
