name: url_launcher_example
description: Demonstrates how to use the url_launcher plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: any
  url_launcher_macos:
    # When depending on this package from a real application you should use:
    #   url_launcher_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  integration_test:
    path: ../../../integration_test
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8"
