name: experimental_connectivity_web
description: An (experimental) implementation for the web platform of the Flutter `connectivity` plugin. This uses the browser's NetworkInformation Web API through Dart's JS interop. Due to privacy concerns, not all features available to Mobile apps are available to Web apps, nor said API is available across all browsers.
version: 0.1.0
homepage: https://github.com/ditman/plugins/tree/connectivity-web/packages/connectivity/connectivity_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ConnectivityPlugin
        fileName: connectivity_web.dart

dependencies:
  connectivity_platform_interface: ^1.0.3
  js: ^0.6.1+1
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  e2e: ^0.2.4+3

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"
