name: camera_web
description: Web platform implementation of camera
homepage: https://github.com/flutter/plugins/tree/master/packages/camera/camera_web

version: 2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CameraPlugin
        fileName: camera_web.dart

dependencies:
  camera_platform_interface: ^2.0.1
  meta: ^1.3.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"
