name: firebase_admob
description: Firebase AdMob plugin for Flutter applications.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_admob
version: 0.8.0

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseadmob
    iosPrefix: FLT
    pluginClass: FirebaseAdMobPlugin

dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  firebase_core: ^0.3.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
