name: firebase_admob
description: Firebase AdMob plugin for Flutter applications.
version: 0.0.2
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_admob

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseadmob
    pluginClass: FirebaseAdMobPlugin

dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.0.2
  test: 0.12.21

environment:
  sdk: ">=1.8.0 <2.0.0"
