name: flutter_plugin_android_lifecycle
description: Flutter plugin for accessing an Android Lifecycle within other plugins.
version: 1.0.4
homepage: https://github.com/flutter/plugins/tree/master/packages/flutter_plugin_android_lifecycle

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.flutter_plugin_android_lifecycle
        pluginClass: FlutterAndroidLifecyclePlugin
