name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_web:
    path: ../

dev_dependencies:
  build_runner: ^2.1.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  google_maps: ^6.1.0
  google_maps_flutter: # Used for projection_test.dart
    path: ../../google_maps_flutter
  http: ^0.13.0
  integration_test:
    sdk: flutter
  mockito: ^5.3.0
