name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  google_maps_flutter_web:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.1
  google_maps: ^5.2.0
  google_maps_flutter: # Used for projection_test.dart
    path: ../../google_maps_flutter
  http: ^0.13.0
  mockito: ^5.0.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
